### ISSUE TITLE
Was compiled against a different Node.js version using

### ISSUE THREAD

**Issue by kvvinokurov** [gandjustas/windows-credman#2]
I am trying to use this solution in webpack.
When I start it, I get an error:

`C:\ListForms>webpack
C:\ListForms\node_modules\webpack-cli\bin\cli.js:93
                                throw err;
                                ^

Error: The module '\\?\C:\ListForms\node_modules\windows-credman\lib\windows-credman-x64.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (C:\ListForms\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:\ListForms\node_modules\windows-credman\index.js:1:80)
    at Module._compile (C:\ListForms\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (C:\ListForms\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:\ListForms\webpack.config.ts:8:17)
    at Module._compile (C:\ListForms\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (C:\ListForms\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (C:\ListForms\node_modules\webpack-cli\bin\utils\convert-argv.js:114:13)
    at requireConfig (C:\ListForms\node_modules\webpack-cli\bin\utils\convert-argv.js:116:6)
    at C:\ListForms\node_modules\webpack-cli\bin\utils\convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\ListForms\node_modules\webpack-cli\bin\utils\convert-argv.js:121:15)
    at yargs.parse (C:\ListForms\node_modules\webpack-cli\bin\cli.js:71:45)
    at Object.parse (C:\ListForms\node_modules\yargs\yargs.js:567:18)
    at C:\ListForms\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.<anonymous> (C:\ListForms\node_modules\webpack-cli\bin\cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\ListForms\node_modules\webpack\bin\webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
`

Versions:
- node: v10.16.3
- npm: 6.11.3
- OS: Windows 10 1803 (build 17134.1006) x64

I tried to manually delete the windows-credman folder in node_modules. Then I ran npm install.
Then: npm rebuild windows-credman --update-binary

Did not help :(

**Comment by stephen-burrows** [comment]
I had the same error. This fixed it for me:
```
npm install node-gyp
cd .\node_modules\windows-credman\
.\rebuild.cmd
```
Note: you have to run the rebuild.cmd from within the windows-credman folder

**Comment by kvvinokurov** [comment]
I get error. I have Internet access behind a corporate proxy server. For npm proxy I have configured. Maybe I need to configure separately for gyp?

`C:\ListForms>cd .\node_modules\windows-credman\

C:\ListForms\node_modules\windows-credman>.\rebuild.cmd

C:\ListForms\node_modules\windows-credman>mkdir lib
A subdirectory or file lib already exists.

C:\ListForms\node_modules\windows-credman>call node-gyp rebuild --arch=x64
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@10.16.3 | win32 | x64
gyp info find Python using Python version 2.7.15 found at "C:\Users\someuser\.windows-build-tools\python27\python.exe"
gyp http GET https://nodejs.org/download/release/v10.16.3/node-v10.16.3-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\ListForms\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--arch=x64"
gyp ERR! cwd C:\ListForms\node_modules\windows-credman
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
File not found - windows-credman.node
0 File(s) copied
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@10.16.3 | win32 | x64
gyp info find Python using Python version 2.7.15 found at "C:\Users\someuser\.windows-build-tools\python27\python.exe"
gyp http GET https://nodejs.org/download/release/v10.16.3/node-v10.16.3-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\ListForms\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--arch=ia32"
gyp ERR! cwd C:\ListForms\node_modules\windows-credman
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
File not found - windows-credman.node
0 File(s) copied
`

[UPDATE]
Yes, this string helped.
`node-gyp configure --proxy=http://[address]:[port]`
